apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: images.example.com
spec:
  preserveUnknownFields: false
  group: example.com
  names:
    kind: Image
    listKind: ImageList
    plural: images
    singular: image
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    additionalPrinterColumns:
    - jsonPath: .spec.image
      description: image
      name: Image
      type: string
    - jsonPath: .status.latestImage
      description: config status
      name: Latest
      type: string
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: Image is the Schema for the image API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ImageSpec defines the desired state of Image
            properties:
              image:
                description: A registry image path, e.g. "nginx" or "gcr.io/my-project/app"
                type: string
              interval:
                description: The interval at which to check for repository updates, e.g. "30s" or "1m30s".
                type: string
            type: object
          status:
            description: ImageStatus defines the observed state of Image
            properties:
              latestImage:
                type: string
              complete:
                type: boolean
              observedGeneration:
                format: int64
                type: integer
            type: object
        type: object
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []